# Generated by Django 6.0.7 on 2026-07-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['tempo'], name='playlist_so_tempo_5bca2c_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['year'], name='playlist_so_year_1316d5_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['popularity'], name='playlist_so_popular_3b8f7d_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['genre'], name='playlist_so_genre_506713_idx'),
        ),
    ]
