# Generated by Django 6.0.7 on 2026-07-26 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_song_playlist_so_tempo_5bca2c_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='song',
            new_name='tempo_idx',
            old_name='playlist_so_tempo_5bca2c_idx',
        ),
        migrations.RenameIndex(
            model_name='song',
            new_name='year_idx',
            old_name='playlist_so_year_1316d5_idx',
        ),
        migrations.RenameIndex(
            model_name='song',
            new_name='popularity_idx',
            old_name='playlist_so_popular_3b8f7d_idx',
        ),
        migrations.RenameIndex(
            model_name='song',
            new_name='genre_idx',
            old_name='playlist_so_genre_506713_idx',
        ),
    ]
