# Generated by Django 6.0.7 on 2026-07-26 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_rename_playlist_so_tempo_5bca2c_idx_tempo_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist',
            new_name='artists',
        ),
    ]
