# Generated by Django 6.0.7 on 2026-07-26 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_rename_artist_song_artists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_tempo', models.FloatField()),
                ('slug', models.CharField(default='Kr2womWBU30', max_length=11, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
                ('songs', models.ManyToManyField(blank=True, related_name='songs', to='playlist.song')),
            ],
        ),
    ]
