# Generated by Django 6.0.7 on 2026-07-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0006_alter_playlist_slug_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-popularity']},
        ),
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.CharField(default='L40h1R3dOjk', max_length=11, unique=True),
        ),
    ]
