# Generated by Django 6.0.7 on 2026-07-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0007_alter_song_options_alter_playlist_slug'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='song',
            name='tempo_idx',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='tempo',
            new_name='pace',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.CharField(default='DXpNgQDwoNA', max_length=11, unique=True),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['pace'], name='pace_idx'),
        ),
    ]
