# Generated by Django 6.0.7 on 2026-07-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0008_remove_song_tempo_idx_rename_tempo_song_pace_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='target_tempo',
            new_name='target_pace',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.CharField(default='GMZLkrZ7EG4', max_length=11, unique=True),
        ),
    ]
