# Generated by Django 6.0.7 on 2026-07-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0009_rename_target_tempo_playlist_target_pace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
